[project]
name = "ishinydex"
version = "0.1.0"
description = ""
authors = [
    {name = "Victor Nunes",email = "victor.gn@defensoria.to.def.br"}
]
requires-python = ">=3.14,<3.15"
dependencies = [
    "django (>=6.0.3,<7.0.0)",
    "djangorestframework (>=3.17.1,<4.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "python-decouple (>=3.8,<4.0)",
    "requests (>=2.32,<3)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "drf-spectacular (>=0.30.0,<0.31.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "django-debug-toolbar (>=7.0.0,<8.0.0)",
    "django-stubs (>=6.0.7,<7.0.0)",
    "djlint (>=1.40.4,<2.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "mypy (>=2.3.0,<3.0.0)",
    "pre-commit (>=4.6.2,<5.0.0)",
]
prod = [
    "uwsgi (>=2.0.31,<3.0.0)"
]

[tool.black]
line-length = 88
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
  | migrations
)/
'''

[tool.mypy]
python_version = "3.14"

plugins = [
    "mypy_django_plugin.main"
]

strict = false
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "ishinydex.settings"

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_django = ["django"]
known_third_party = ["corsheaders", "decouple", "drf_spectacular", "requests", "rest_framework", "urllib3"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = 3
skip = [".gitignore", ".dockerignore", ".venv", "migrations"]
