# Generated by Django 6.0.3 on 2026-07-02 03:32

import django.db.models.deletion
import home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('position', models.PositiveIntegerField(editable=False, verbose_name='position')),
            ],
            options={
                'verbose_name': 'box',
                'verbose_name_plural': 'boxes',
            },
        ),
        migrations.CreateModel(
            name='OriginalTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('trainer_id', models.CharField(max_length=255, verbose_name='trainer ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.version')),
            ],
            options={
                'ordering': ('version__version_group__order',),
            },
        ),
        migrations.CreateModel(
            name='PersonalDex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('is_shiny_dex', models.BooleanField(default=False, verbose_name='is shiny dex')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forms', models.ManyToManyField(blank=True, to='pokedex.pokemonform')),
            ],
            options={
                'verbose_name': 'personal dex',
                'verbose_name_plural': 'personal dex',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='nickname')),
                ('language', models.CharField(default='en', max_length=255, verbose_name='language')),
                ('gender', models.CharField(default='genderless', max_length=255, verbose_name='gender')),
                ('nature', models.CharField(default='hardy', max_length=255, verbose_name='nature')),
                ('is_alpha', models.BooleanField(default=False, verbose_name='is alpha')),
                ('is_shiny', models.BooleanField(default=False, verbose_name='is shiny')),
                ('captured_at', models.DateField(verbose_name='captured at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemonform')),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.originaltrainer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(choices=home.utils.row_choices, verbose_name='row')),
                ('col', models.IntegerField(choices=home.utils.col_choices, verbose_name='col')),
                ('position', models.PositiveIntegerField(editable=False, verbose_name='position')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='home.box')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pokemonform')),
                ('personal_dex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.personaldex')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.specimen')),
            ],
            options={
                'verbose_name': 'slot',
                'verbose_name_plural': 'slots',
                'ordering': ['box__position', 'row', 'col'],
                'unique_together': {('box', 'row', 'col')},
            },
        ),
    ]
