# Generated by Django 6.0.3 on 2026-06-18 17:58

import django.db.models.deletion
import home.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(editable=False, verbose_name='position')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'box',
                'verbose_name_plural': 'boxes',
            },
        ),
        migrations.CreateModel(
            name='PokemonSpecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ndex_id', models.PositiveIntegerField(unique=True, verbose_name='national dex number')),
                ('species', models.CharField(max_length=255, verbose_name='species')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='nickname')),
                ('language', models.CharField(default='en', max_length=255, verbose_name='language')),
                ('gender', models.CharField(default='genderless', max_length=255, verbose_name='gender')),
                ('form', models.CharField(blank=True, max_length=255, null=True, verbose_name='form')),
                ('is_gmax', models.BooleanField(default=False, verbose_name='is gmax')),
                ('is_legendary', models.BooleanField(default=False, verbose_name='is legendary')),
                ('is_mega', models.BooleanField(default=False, verbose_name='is mega')),
                ('is_mythical', models.BooleanField(default=False, verbose_name='is mythical')),
                ('is_shiny', models.BooleanField(default=False, verbose_name='is shiny')),
                ('ot_name', models.CharField(max_length=255, verbose_name='original trainer name')),
                ('ot_id', models.CharField(max_length=255, verbose_name='original trainer ID')),
                ('og_generation', models.CharField(max_length=255, verbose_name='game generation')),
                ('og_version_group', models.CharField(max_length=255, verbose_name='game version group')),
                ('og_version_name', models.CharField(max_length=255, verbose_name='game version name')),
                ('captured_at', models.DateField(verbose_name='captured at')),
            ],
            options={
                'verbose_name': 'pokémon specimen',
                'verbose_name_plural': 'pokémon specimens',
            },
        ),
        migrations.CreateModel(
            name='PersonalDex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('boxes', models.ManyToManyField(blank=True, to='home.box')),
                ('forms', models.ManyToManyField(blank=True, to='pokedex.pokemonform')),
            ],
            options={
                'verbose_name': 'personal dex',
                'verbose_name_plural': 'personal dex',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(editable=False, verbose_name='position')),
                ('row', models.IntegerField(choices=home.utils.row_choices, verbose_name='row')),
                ('col', models.IntegerField(choices=home.utils.col_choices, verbose_name='col')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='home.box')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.pokemonspecimen')),
            ],
            options={
                'verbose_name': 'slot',
                'verbose_name_plural': 'slots',
                'ordering': ['box__position', 'row', 'col'],
                'unique_together': {('box', 'row', 'col')},
            },
        ),
    ]
