# Generated by Django 6.0.3 on 2026-07-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personaldex",
            options={
                "verbose_name": "personal dex",
                "verbose_name_plural": "personal dexes",
            },
        ),
    ]
