# Generated by Django 6.0.3 on 2026-07-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slot",
            options={
                "ordering": ("box__position", "position"),
                "verbose_name": "slot",
                "verbose_name_plural": "slots",
            },
        ),
    ]
