# Generated by Django 6.0.3 on 2026-08-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimen",
            name="pokeball",
            field=models.CharField(
                blank=True,
                choices=[
                    ("poke-ball", "Poké Ball"),
                    ("great-ball", "Great Ball"),
                    ("ultra-ball", "Ultra Ball"),
                    ("master-ball", "Master Ball"),
                    ("premier-ball", "Premier Ball"),
                    ("heal-ball", "Heal Ball"),
                    ("net-ball", "Net Ball"),
                    ("nest-ball", "Nest Ball"),
                    ("dive-ball", "Dive Ball"),
                    ("dusk-ball", "Dusk Ball"),
                    ("timer-ball", "Timer Ball"),
                    ("quick-ball", "Quick Ball"),
                    ("repeat-ball", "Repeat Ball"),
                    ("luxury-ball", "Luxury Ball"),
                    ("fast-ball", "Fast Ball"),
                    ("friend-ball", "Friend Ball"),
                    ("lure-ball", "Lure Ball"),
                    ("level-ball", "Level Ball"),
                    ("heavy-ball", "Heavy Ball"),
                    ("love-ball", "Love Ball"),
                    ("moon-ball", "Moon Ball"),
                    ("dream-ball", "Dream Ball"),
                    ("sport-ball", "Sport Ball"),
                    ("safari-ball", "Safari Ball"),
                    ("beast-ball", "Beast Ball"),
                    ("cherish-ball", "Cherish Ball"),
                    ("lapoke-ball", "Poké Ball"),
                    ("lagreat-ball", "Great Ball"),
                    ("laultra-ball", "Ultra Ball"),
                    ("lafeather-ball", "Feather Ball"),
                    ("lawing-ball", "Wing Ball"),
                    ("lajet-ball", "Jet Ball"),
                    ("laheavy-ball", "Heavy Ball"),
                    ("laleaden-ball", "Leaden Ball"),
                    ("lagigaton-ball", "Gigaton Ball"),
                    ("laorigin-ball", "Origin Ball"),
                ],
                max_length=255,
                null=True,
                verbose_name="pokéball",
            ),
        ),
    ]
