# Generated by Django 6.0.3 on 2026-08-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_personaldex_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimen",
            name="language",
            field=models.CharField(
                choices=[
                    ("ja-hrkt", "ja-hrkt"),
                    ("ja-roma", "ja-roma"),
                    ("ko", "ko"),
                    ("zh-hant", "zh-hant"),
                    ("fr", "fr"),
                    ("de", "de"),
                    ("es", "es"),
                    ("it", "it"),
                    ("en", "en"),
                    ("cs", "cs"),
                    ("ja", "ja"),
                    ("zh-hans", "zh-hans"),
                    ("pt-br", "pt-br"),
                    ("es-419", "es-419"),
                ],
                default="en",
                verbose_name="language",
            ),
        ),
    ]
