# Generated by Django 6.0.3 on 2026-09-30 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_specimen_pokeball"),
        ("pokedex", "0005_unique_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimen",
            name="origin_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origin_specimens",
                to="pokedex.version",
                verbose_name="origin game",
            ),
        ),
    ]
