# Generated by Django 6.0.3 on 2026-07-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_slot_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimen",
            name="gender",
            field=models.CharField(
                default="male", max_length=255, verbose_name="gender"
            ),
        ),
    ]
