# Generated by Django 6.0.3 on 2026-08-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_specimen_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimen",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("genderless", "genderless"),
                ],
                default="male",
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="nature",
            field=models.CharField(
                choices=[
                    ("adamant", "adamant"),
                    ("bashful", "bashful"),
                    ("bold", "bold"),
                    ("brave", "brave"),
                    ("calm", "calm"),
                    ("careful", "careful"),
                    ("docile", "docile"),
                    ("gentle", "gentle"),
                    ("hardy", "hardy"),
                    ("hasty", "hasty"),
                    ("impish", "impish"),
                    ("jolly", "jolly"),
                    ("lax", "lax"),
                    ("lonely", "lonely"),
                    ("mild", "mild"),
                    ("modest", "modest"),
                    ("naive", "naive"),
                    ("naughty", "naughty"),
                    ("quiet", "quiet"),
                    ("quirky", "quirky"),
                    ("rash", "rash"),
                    ("relaxed", "relaxed"),
                    ("sassy", "sassy"),
                    ("serious", "serious"),
                    ("timid", "timid"),
                ],
                default="hardy",
                verbose_name="nature",
            ),
        ),
    ]
