# Generated by Django 6.0.3 on 2026-07-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_specimen_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimen",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="observation"),
        ),
    ]
