# Generated by Django 6.0.3 on 2026-10-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_fill_specimen_origin_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specimen",
            options={
                "ordering": (
                    "form__pokemon__species__id",
                    "form__form_order",
                    "form__pk",
                ),
                "verbose_name": "specimen",
                "verbose_name_plural": "specimens",
            },
        ),
    ]
