# Generated by Django 6.0.3 on 2026-10-01 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_specimen_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimen",
            name="location_since",
            field=models.DateField(
                blank=True, null=True, verbose_name="location since"
            ),
        ),
        migrations.CreateModel(
            name="Save",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=255, verbose_name="label"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="save_file",
                        to="home.originaltrainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "save",
                "verbose_name_plural": "saves",
                "ordering": (
                    "trainer__version__version_group__order",
                    "trainer__version__name",
                    "pk",
                ),
            },
        ),
        migrations.AddField(
            model_name="specimen",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="home.save",
                verbose_name="location",
            ),
        ),
    ]
