# Generated by Django 6.0.3 on 2026-10-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_save_and_specimen_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="box",
            options={
                "ordering": ["position"],
                "verbose_name": "box",
                "verbose_name_plural": "boxes",
            },
        ),
    ]
