# Generated by Django 6.0.3 on 2026-08-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "accuracy",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="accuracy"
                    ),
                ),
                (
                    "effect_chance",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="effect chance"
                    ),
                ),
                ("pp", models.PositiveIntegerField(verbose_name="pp")),
                ("priority", models.IntegerField(verbose_name="priority")),
                (
                    "power",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="power"
                    ),
                ),
                (
                    "damage_class",
                    models.CharField(max_length=255, verbose_name="damage class"),
                ),
                (
                    "generation",
                    models.CharField(max_length=255, verbose_name="game generation"),
                ),
                ("target", models.CharField(max_length=255, verbose_name="target")),
                ("type", models.CharField(max_length=255, verbose_name="type")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "move",
                "verbose_name_plural": "moves",
            },
        ),
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=255, verbose_name="language"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "name",
                "verbose_name_plural": "names",
            },
        ),
        migrations.CreateModel(
            name="PokemonFormType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.PositiveIntegerField(verbose_name="slot")),
                ("type", models.CharField(max_length=255, verbose_name="type")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pokémon form type",
                "verbose_name_plural": "pokémon form types",
                "ordering": ("slot",),
            },
        ),
        migrations.CreateModel(
            name="PokemonMoveVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "move_learn_method",
                    models.CharField(max_length=255, verbose_name="move learn method"),
                ),
                (
                    "level_learned_at",
                    models.PositiveIntegerField(verbose_name="level learned at"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pokémon move version",
                "verbose_name_plural": "pokémon move versions",
            },
        ),
        migrations.CreateModel(
            name="PokemonSpeciesDexEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_number",
                    models.PositiveIntegerField(verbose_name="entry number"),
                ),
                ("pokedex", models.CharField(max_length=255, verbose_name="pokédex")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pokémon species dex entry",
                "verbose_name_plural": "pokémon species dex entries",
            },
        ),
        migrations.CreateModel(
            name="PokemonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat", models.CharField(max_length=255, verbose_name="stat")),
                ("effort", models.PositiveIntegerField(verbose_name="effort")),
                ("base_stat", models.PositiveIntegerField(verbose_name="base stat")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pokémon stat",
                "verbose_name_plural": "pokémon stats",
            },
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.PositiveIntegerField(verbose_name="slot")),
                ("type", models.CharField(max_length=255, verbose_name="type")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pokémon type",
                "verbose_name_plural": "pokémon types",
                "ordering": ("slot",),
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "version",
                "verbose_name_plural": "versions",
                "ordering": ("version_group__order",),
            },
        ),
        migrations.CreateModel(
            name="VersionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "generation",
                    models.CharField(max_length=255, verbose_name="game generation"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="order")),
                ("pokedexes", models.JSONField(default=list, verbose_name="pokédexes")),
                ("regions", models.JSONField(default=list, verbose_name="regions")),
                ("versions", models.JSONField(default=list, verbose_name="versions")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "version group",
                "verbose_name_plural": "version groups",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.PositiveIntegerField(verbose_name="slot")),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="is hidden"),
                ),
                ("ability", models.CharField(max_length=255, verbose_name="ability")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pokémon ability",
                "verbose_name_plural": "pokémon abilities",
                "unique_together": {("slot", "ability", "is_hidden")},
            },
        ),
        migrations.CreateModel(
            name="PokemonMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pokedex.move"
                    ),
                ),
                (
                    "version_group_details",
                    models.ManyToManyField(
                        related_name="moves", to="pokedex.pokemonmoveversion"
                    ),
                ),
            ],
            options={
                "verbose_name": "pokémon move",
                "verbose_name_plural": "pokémon moves",
            },
        ),
        migrations.CreateModel(
            name="PokemonSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("order", models.PositiveIntegerField(verbose_name="order")),
                ("gender_rate", models.IntegerField(verbose_name="gender rate")),
                (
                    "capture_rate",
                    models.PositiveIntegerField(verbose_name="capture rate"),
                ),
                (
                    "base_happiness",
                    models.PositiveIntegerField(verbose_name="base happiness"),
                ),
                ("is_baby", models.BooleanField(default=False, verbose_name="is baby")),
                (
                    "is_legendary",
                    models.BooleanField(default=False, verbose_name="is legendary"),
                ),
                (
                    "is_mythical",
                    models.BooleanField(default=False, verbose_name="is mythical"),
                ),
                (
                    "hatch_counter",
                    models.PositiveIntegerField(verbose_name="hatch counter"),
                ),
                (
                    "has_gender_differences",
                    models.BooleanField(
                        default=False, verbose_name="has gender differences"
                    ),
                ),
                (
                    "forms_switchable",
                    models.BooleanField(default=False, verbose_name="forms switchable"),
                ),
                (
                    "growth_rate",
                    models.CharField(max_length=255, verbose_name="growth rate"),
                ),
                (
                    "egg_groups",
                    models.JSONField(default=list, verbose_name="egg groups"),
                ),
                ("color", models.CharField(max_length=255, verbose_name="color")),
                ("shape", models.CharField(max_length=255, verbose_name="shape")),
                (
                    "generation",
                    models.CharField(max_length=255, verbose_name="game generation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evolves_from_species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evolves_to_species",
                        to="pokedex.pokemonspecies",
                    ),
                ),
                (
                    "names",
                    models.ManyToManyField(
                        related_name="pokemon_species_names", to="pokedex.name"
                    ),
                ),
                (
                    "pokedex_numbers",
                    models.ManyToManyField(
                        related_name="pokemon_species",
                        to="pokedex.pokemonspeciesdexentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "pokémon species",
                "verbose_name_plural": "pokémon species",
            },
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "pokeapi_id",
                    models.PositiveIntegerField(default=1, verbose_name="PokéAPI ID"),
                ),
                (
                    "base_experience",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="base experience"
                    ),
                ),
                ("height", models.PositiveIntegerField(verbose_name="height")),
                (
                    "is_default",
                    models.BooleanField(default=True, verbose_name="is default"),
                ),
                ("order", models.IntegerField(verbose_name="order")),
                ("weight", models.PositiveIntegerField(verbose_name="weight")),
                ("sprites", models.JSONField(default=dict, verbose_name="sprites")),
                ("cries", models.JSONField(default=dict, verbose_name="cries")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abilities",
                    models.ManyToManyField(
                        related_name="pokemons", to="pokedex.pokemonability"
                    ),
                ),
                (
                    "moves",
                    models.ManyToManyField(
                        related_name="pokemons", to="pokedex.pokemonmove"
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemons",
                        to="pokedex.pokemonspecies",
                    ),
                ),
                (
                    "stats",
                    models.ManyToManyField(
                        related_name="pokemons", to="pokedex.pokemonstat"
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        related_name="pokemons", to="pokedex.pokemontype"
                    ),
                ),
            ],
            options={
                "verbose_name": "pokémon",
                "verbose_name_plural": "pokémons",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="PokemonSpeciesVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=True, verbose_name="is default"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon_species_varieties",
                        to="pokedex.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name": "pokémon species variety",
                "verbose_name_plural": "pokémon species varieties",
            },
        ),
        migrations.AddField(
            model_name="pokemonspecies",
            name="varieties",
            field=models.ManyToManyField(
                related_name="pokemon_species_varieties",
                to="pokedex.pokemonspeciesvariety",
            ),
        ),
        migrations.CreateModel(
            name="VersionGameIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_index", models.PositiveIntegerField(verbose_name="game index")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokedex.version",
                    ),
                ),
            ],
            options={
                "verbose_name": "version game index",
                "verbose_name_plural": "version game indexes",
            },
        ),
        migrations.AddField(
            model_name="pokemon",
            name="game_indices",
            field=models.ManyToManyField(
                related_name="pokemons", to="pokedex.versiongameindex"
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="version_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pokedex.versiongroup"
            ),
        ),
        migrations.AddField(
            model_name="pokemonmoveversion",
            name="version_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pokedex.versiongroup"
            ),
        ),
        migrations.CreateModel(
            name="PokemonForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("pokeapi_id", models.PositiveIntegerField(verbose_name="PokéAPI ID")),
                ("order", models.PositiveIntegerField(verbose_name="order")),
                ("form_order", models.PositiveIntegerField(verbose_name="form order")),
                (
                    "is_default",
                    models.BooleanField(default=True, verbose_name="is default"),
                ),
                (
                    "is_battle_only",
                    models.BooleanField(default=False, verbose_name="is battle only"),
                ),
                ("is_mega", models.BooleanField(default=False, verbose_name="is mega")),
                (
                    "form_name",
                    models.CharField(max_length=255, verbose_name="form name"),
                ),
                ("sprites", models.JSONField(default=dict, verbose_name="sprites")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_names",
                    models.ManyToManyField(
                        related_name="pokemon_forms_form_names", to="pokedex.name"
                    ),
                ),
                (
                    "names",
                    models.ManyToManyField(
                        related_name="pokemon_forms_names", to="pokedex.name"
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="pokedex.pokemon",
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        related_name="pokemon_forms", to="pokedex.pokemonformtype"
                    ),
                ),
                (
                    "version_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon_forms",
                        to="pokedex.versiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "pokémon form",
                "verbose_name_plural": "pokémon forms",
            },
        ),
    ]
