# Generated by Django 6.0.3 on 2026-06-15 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('accuracy', models.PositiveIntegerField(blank=True, null=True, verbose_name='accuracy')),
                ('effect_chance', models.PositiveIntegerField(blank=True, null=True, verbose_name='effect chance')),
                ('pp', models.PositiveIntegerField(verbose_name='pp')),
                ('priority', models.IntegerField(verbose_name='priority')),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='power')),
                ('damage_class', models.CharField(max_length=255, verbose_name='damage class')),
                ('generation', models.CharField(max_length=255, verbose_name='game generation')),
                ('target', models.CharField(max_length=255, verbose_name='target')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('language', models.CharField(default='en', max_length=255, verbose_name='language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonFormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.PositiveIntegerField(verbose_name='slot')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonMoveVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move_learn_method', models.CharField(max_length=255, verbose_name='move learn method')),
                ('version_group', models.CharField(max_length=255, verbose_name='game version group')),
                ('level_learned_at', models.PositiveIntegerField(verbose_name='level learned at')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonSpeciesDexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.PositiveIntegerField(verbose_name='entry number')),
                ('pokedex', models.CharField(max_length=255, verbose_name='pokedex')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stat', models.CharField(max_length=255, verbose_name='stat')),
                ('effort', models.PositiveIntegerField(verbose_name='effort')),
                ('base_stat', models.PositiveIntegerField(verbose_name='base stat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.PositiveIntegerField(verbose_name='slot')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
            ],
            options={
                'ordering': ('slot',),
            },
        ),
        migrations.CreateModel(
            name='VersionGameIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_index', models.PositiveIntegerField(verbose_name='game index')),
                ('version', models.CharField(max_length=255, verbose_name='game version')),
            ],
            options={
                'verbose_name_plural': 'Version game indices',
            },
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.PositiveIntegerField(verbose_name='slot')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='is hidden')),
                ('ability', models.CharField(max_length=255, verbose_name='ability')),
            ],
            options={
                'verbose_name_plural': 'Pokemon abilities',
                'unique_together': {('slot', 'ability', 'is_hidden')},
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('base_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='base experience')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('is_default', models.BooleanField(default=True, verbose_name='is default')),
                ('order', models.IntegerField(verbose_name='order')),
                ('weight', models.PositiveIntegerField(verbose_name='weight')),
                ('sprites', models.JSONField(default=dict, verbose_name='sprites')),
                ('cries', models.JSONField(default=dict, verbose_name='cries')),
                ('abilities', models.ManyToManyField(related_name='pokemons', to='pokedex.pokemonability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('form_order', models.PositiveIntegerField(verbose_name='form order')),
                ('is_default', models.BooleanField(default=True, verbose_name='is default')),
                ('is_battle_only', models.BooleanField(default=False, verbose_name='is battle only')),
                ('is_mega', models.BooleanField(default=False, verbose_name='is mega')),
                ('form_name', models.CharField(max_length=255, verbose_name='form name')),
                ('sprites', models.JSONField(default=dict, verbose_name='sprites')),
                ('version_group', models.CharField(max_length=255, verbose_name='game version group')),
                ('form_names', models.ManyToManyField(related_name='pokemon_forms_form_names', to='pokedex.name')),
                ('names', models.ManyToManyField(related_name='pokemon_forms_names', to='pokedex.name')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='pokedex.pokemon')),
                ('types', models.ManyToManyField(related_name='pokemon_forms', to='pokedex.pokemonformtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.move')),
                ('version_group_details', models.ManyToManyField(related_name='moves', to='pokedex.pokemonmoveversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(related_name='pokemons', to='pokedex.pokemonmove'),
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('gender_rate', models.IntegerField(verbose_name='gender rate')),
                ('capture_rate', models.PositiveIntegerField(verbose_name='capture rate')),
                ('base_happiness', models.PositiveIntegerField(verbose_name='base happiness')),
                ('is_baby', models.BooleanField(default=False, verbose_name='is baby')),
                ('is_legendary', models.BooleanField(default=False, verbose_name='is legendary')),
                ('is_mythical', models.BooleanField(default=False, verbose_name='is mythical')),
                ('hatch_counter', models.PositiveIntegerField(verbose_name='hatch counter')),
                ('has_gender_differences', models.BooleanField(default=False, verbose_name='has gender differences')),
                ('forms_switchable', models.BooleanField(default=False, verbose_name='forms switchable')),
                ('growth_rate', models.CharField(max_length=255, verbose_name='growth rate')),
                ('egg_groups', models.JSONField(default=list, verbose_name='egg groups')),
                ('color', models.CharField(max_length=255, verbose_name='color')),
                ('shape', models.CharField(max_length=255, verbose_name='shape')),
                ('generation', models.CharField(max_length=255, verbose_name='game generation')),
                ('evolves_from_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_to_species', to='pokedex.pokemonspecies')),
                ('names', models.ManyToManyField(related_name='pokemon_species_names', to='pokedex.name')),
                ('pokedex_numbers', models.ManyToManyField(related_name='pokemon_species', to='pokedex.pokemonspeciesdexentry')),
            ],
            options={
                'verbose_name_plural': 'Pokemon species',
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='pokedex.pokemonspecies'),
        ),
        migrations.CreateModel(
            name='PokemonSpeciesVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=True, verbose_name='is default')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_species_varieties', to='pokedex.pokemon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='varieties',
            field=models.ManyToManyField(related_name='pokemon_species_varieties', to='pokedex.pokemonspeciesvariety'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.ManyToManyField(related_name='pokemons', to='pokedex.pokemonstat'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemons', to='pokedex.pokemontype'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='game_indices',
            field=models.ManyToManyField(related_name='pokemons', to='pokedex.versiongameindex'),
        ),
    ]
