# Generated by Django 6.0.3 on 2026-07-16 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemon",
            options={"ordering": ("order",)},
        ),
    ]
