# Generated by Django 6.0.3 on 2026-08-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemonform",
            options={
                "ordering": ("pokemon__species", "form_order"),
                "verbose_name": "pokémon form",
                "verbose_name_plural": "pokémon forms",
            },
        ),
        migrations.CreateModel(
            name="ShinyLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        max_length=50, unique=True, verbose_name="caption"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "lock_type",
                    models.CharField(
                        choices=[
                            ("distro-only", "distro only"),
                            ("unobtainable", "unobtainable"),
                        ],
                        default="distro-only",
                        verbose_name="lock type",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "forms",
                    models.ManyToManyField(
                        related_name="shinylocks", to="pokedex.pokemonform"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
