# Generated by Django 6.0.3 on 2026-07-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="move",
            options={"verbose_name": "move", "verbose_name_plural": "moves"},
        ),
        migrations.AlterModelOptions(
            name="name",
            options={"verbose_name": "name", "verbose_name_plural": "names"},
        ),
        migrations.AlterModelOptions(
            name="pokemon",
            options={
                "ordering": ("order",),
                "verbose_name": "pokémon",
                "verbose_name_plural": "pokémons",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonability",
            options={
                "verbose_name": "pokémon ability",
                "verbose_name_plural": "pokémon abilities",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonform",
            options={
                "ordering": ("pokemon__species__order", "order"),
                "verbose_name": "pokémon form",
                "verbose_name_plural": "pokémon forms",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonformtype",
            options={
                "ordering": ("slot",),
                "verbose_name": "pokémon form type",
                "verbose_name_plural": "pokémon form types",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonmove",
            options={
                "verbose_name": "pokémon move",
                "verbose_name_plural": "pokémon moves",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonmoveversion",
            options={
                "verbose_name": "pokémon move version",
                "verbose_name_plural": "pokémon move versions",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonspecies",
            options={
                "verbose_name": "pokémon species",
                "verbose_name_plural": "pokémon species",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonspeciesdexentry",
            options={
                "verbose_name": "pokémon species dex entry",
                "verbose_name_plural": "pokémon species dex entries",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonspeciesvariety",
            options={
                "verbose_name": "pokémon species variety",
                "verbose_name_plural": "pokémon species varieties",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemonstat",
            options={
                "verbose_name": "pokémon stat",
                "verbose_name_plural": "pokémon stats",
            },
        ),
        migrations.AlterModelOptions(
            name="pokemontype",
            options={
                "ordering": ("slot",),
                "verbose_name": "pokémon type",
                "verbose_name_plural": "pokémon types",
            },
        ),
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": ("version_group__order",),
                "verbose_name": "version",
                "verbose_name_plural": "versions",
            },
        ),
        migrations.AlterModelOptions(
            name="versiongameindex",
            options={
                "verbose_name": "version game index",
                "verbose_name_plural": "version game indexes",
            },
        ),
        migrations.AlterModelOptions(
            name="versiongroup",
            options={
                "ordering": ("order",),
                "verbose_name": "version group",
                "verbose_name_plural": "version groups",
            },
        ),
    ]
