# Generated by Django 6.0.3 on 2026-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0002_alter_pokemonform_options_shinylock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shinylock",
            name="caption",
            field=models.CharField(max_length=50, unique=True, verbose_name="caption"),
        ),
    ]
