# Generated by Django 6.0.3 on 2026-08-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0003_alter_shinylock_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shinylock",
            name="lock_type",
            field=models.CharField(
                choices=[
                    ("distro-only", "distro only"),
                    ("unobtainable", "unobtainable"),
                ],
                default="unobtainable",
                verbose_name="lock type",
            ),
        ),
    ]
