# Generated by Django 6.0.3 on 2026-09-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0004_alter_shinylock_lock_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="pokemonform",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="pokemonspecies",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="version",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="versiongroup",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
    ]
