# Generated by Django 6.0.3 on 2026-10-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0005_unique_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemonform",
            options={
                "ordering": ("pokemon__species__id", "form_order", "pk"),
                "verbose_name": "pokémon form",
                "verbose_name_plural": "pokémon forms",
            },
        ),
    ]
