# Generated by Django 6.0.3 on 2026-04-04 01:02

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(editable=False, verbose_name='position')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'box',
                'verbose_name_plural': 'boxes',
            },
        ),
        migrations.CreateModel(
            name='BoxSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(choices=core.utils.row_choices, verbose_name='row')),
                ('col', models.IntegerField(choices=core.utils.col_choices, verbose_name='col')),
                ('pokemon', models.CharField(blank=True, max_length=200, null=True, verbose_name='pokemon')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.box')),
            ],
            options={
                'verbose_name': 'slot',
                'verbose_name_plural': 'slots',
                'ordering': ['box__position', 'row', 'col'],
                'unique_together': {('box', 'row', 'col')},
            },
        ),
    ]
