GEN_FIRST_FORM_NAMES = (
    "bulbasaur",
    "chikorita",
    "treecko",
    "turtwig",
    "victini",
    "chespin",
    "rowlet",
    "grookey",
    "sprigatito",
)

GENDER_CHOICES = (
    ("male", "male"),
    ("female", "female"),
    ("genderless", "genderless"),
)

NATURE_CHOICES = [
    ("adamant", "adamant"),
    ("bashful", "bashful"),
    ("bold", "bold"),
    ("brave", "brave"),
    ("calm", "calm"),
    ("careful", "careful"),
    ("docile", "docile"),
    ("gentle", "gentle"),
    ("hardy", "hardy"),
    ("hasty", "hasty"),
    ("impish", "impish"),
    ("jolly", "jolly"),
    ("lax", "lax"),
    ("lonely", "lonely"),
    ("mild", "mild"),
    ("modest", "modest"),
    ("naive", "naive"),
    ("naughty", "naughty"),
    ("quiet", "quiet"),
    ("quirky", "quirky"),
    ("rash", "rash"),
    ("relaxed", "relaxed"),
    ("sassy", "sassy"),
    ("serious", "serious"),
    ("timid", "timid"),
]


TYPES_DICT = {
    "normal": 1,
    "fighting": 2,
    "flying": 3,
    "poison": 4,
    "ground": 5,
    "rock": 6,
    "bug": 7,
    "ghost": 8,
    "steel": 9,
    "fire": 10,
    "water": 11,
    "grass": 12,
    "electric": 13,
    "psychic": 14,
    "ice": 15,
    "dragon": 16,
    "dark": 17,
    "fairy": 18,
    "stellar": 19,
    "unknown": 10001,
    "shadow": 10002,
}

LANGUAGES_CHOICES = (
    ("ja-hrkt", "ja-hrkt"),
    ("ja-roma", "ja-roma"),
    ("ko", "ko"),
    ("zh-hant", "zh-hant"),
    ("fr", "fr"),
    ("de", "de"),
    ("es", "es"),
    ("it", "it"),
    ("en", "en"),
    ("cs", "cs"),
    ("ja", "ja"),
    ("zh-hans", "zh-hans"),
    ("pt-br", "pt-br"),
    ("es-419", "es-419"),
)
