[uwsgi]
base = /home/guest/django-pokedex
app = wsgi

processes = 10
max-requests = 4000
limit-as = 1024
buffer-size = 32768
listen = 1024
enable-threads = true

pythonpath = %(base)/src
http-socket = 0.0.0.0:8000
chmod-socket = 666
vaccum = true
module = django_pokedex.%(app):application
master = true

; testando para resolver o problema de atestados validados retornando para análise
; https://stackoverflow.com/questions/36156887/uwsgi-raises-oserror-write-error-during-large-request
disable-write-exception

static-map = /static=%(base)/src/staticfiles
static-expires = /* 7776000
offload-threads = %k
