"""
Django settings for ishinydex project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)


ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    cast=lambda v: [s.strip() for s in v.split(",")],
    default="127.0.0.1,localhost",
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party apps
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    # local apps
    "core",
    "home",
    "pokedex",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ishinydex.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.environment",
            ],
        },
    },
]

WSGI_APPLICATION = "ishinydex.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("POSTGRES_DB", default="ishinydex"),
        "USER": config("POSTGRES_USER", default="postgres"),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "HOST": config("POSTGRES_HOST", default="db"),
        "PORT": config("POSTGRES_PORT", cast=int, default=5432),
    },
    "backup": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "%s_backup" % config("POSTGRES_DB", default="ishinydex"),
        "USER": config("POSTGRES_USER", default="postgres"),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "HOST": config("POSTGRES_HOST", default="db"),
        "PORT": config("POSTGRES_PORT", cast=int, default=5432),
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Araguaina"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("pt-br", "Português Brasileiro"),
]

LOCALE_PATHS = ((BASE_DIR / "locale"),)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
# https://docs.djangoproject.com/en/6.0/ref/settings/#media-root

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Database backups (backupdb / restoredb)
BACKUPS_DIR = BASE_DIR.parent / "backups"

# PokéAPI (sync_pokeapi)
# POKEAPI_URL pode apontar para uma instância local da PokéAPI; se ela estiver
# inacessível (e DEBUG=False), o cliente recorre à API oficial.
POKEAPI_URL = config("POKEAPI_URL", default="https://pokeapi.co")
POKEAPI_CACHE_DIR = BASE_DIR.parent / ".cache" / "pokeapi"

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Token primeiro: requisições sem credenciais recebem 401 (com
        # WWW-Authenticate) em vez de 403.
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "api.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "iShinyDex API",
    "DESCRIPTION": "API do iShinyDex (PersonalDex, HOME e Pokédex).",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

# CORS (frontend Flutter)
# FRONTEND_ORIGINS: origens separadas por vírgula (ex.: https://app.exemplo.com).
# Em DEBUG, qualquer http://localhost:<porta> também é aceito (o `flutter run`
# usa portas variáveis).
CORS_ALLOWED_ORIGINS = config(
    "FRONTEND_ORIGINS",
    cast=lambda v: [s.strip() for s in v.split(",") if s.strip()],
    default="",
)
CORS_ALLOWED_ORIGIN_REGEXES = (
    [r"^http://localhost:\d+$", r"^http://127\.0\.0\.1:\d+$"] if DEBUG else []
)

# DATA_UPLOAD_MAX_NUMBER_FIELDS
# https://docs.djangoproject.com/en/6.0/ref/settings/#data-upload-max-number-fields
DATA_UPLOAD_MAX_NUMBER_FIELDS = 3000

# First Party ENVS
SPRITE_RENDERERS = {
    "default": "pokedex.renderers.PokemonSpriteRenderer",
    "pokemon": "pokedex.renderers.HomeSpriteRenderer",
    "pokemonform": "pokedex.renderers.PokemonSpriteRenderer",
    "slot": "pokedex.renderers.HomeSpriteRenderer",
}

POKEMON_SPRITE_RESOLVERS = {
    "default": "pokedex.resolvers.PokemonSpriteResolver",
    "sinistea": "pokedex.resolvers.SingleSpriteResolver",
    "polteageist": "pokedex.resolvers.SingleSpriteResolver",
    "poltchageist": "pokedex.resolvers.SingleSpriteResolver",
    "sinistcha": "pokedex.resolvers.SingleSpriteResolver",
}

SPRITES_ROOT = MEDIA_ROOT / "sprites"
SPRITES_URL = Path(MEDIA_URL) / "sprites"

ITEM_SPRITES_ROOT = SPRITES_ROOT / "items"
ITEM_SPRITES_URL = SPRITES_URL / "items"

POKEMON_SPRITES_ROOT = SPRITES_ROOT / "pokemon"
POKEMON_SPRITES_URL = SPRITES_URL / "pokemon"

TYPE_SPRITES_DEFAULT_GAME = "sword-shield"
TYPE_SPRITES_DEFAULT_GEN = "generation-viii"
TYPE_SPRITES_ROOT = SPRITES_ROOT / "types"
TYPE_SPRITES_URL = SPRITES_URL / "types"

# django-debug-toolbar é dependência de desenvolvimento: só é carregado quando
# habilitado, para que a imagem de produção funcione sem o grupo "dev".
DEBUG_TOOLBAR = DEBUG and config("DEBUG_TOOLBAR", default=False, cast=bool)

if DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.insert(
        MIDDLEWARE.index("django.middleware.common.CommonMiddleware") + 1,
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    )
    DEBUG_TOOLBAR_CONFIG = {"SHOW_TOOLBAR_CALLBACK": lambda _: True}
